apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingest-service
  namespace: kafka
  labels:
    app: ingest-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingest-service
  template:
    metadata:
      labels:
        app: ingest-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9100"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: ingest-service
          image: ingest-service:1.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50051
              name: grpc
            - containerPort: 9100
              name: metrics
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka.kafka.svc.cluster.local:9092"
            - name: GRPC_PORT
              value: "50051"
            - name: METRICS_PORT
              value: "9100"
          resources:
            requests:
              memory: 64Mi
              cpu: 100m
            limits:
              memory: 128Mi
              cpu: 250m
---
apiVersion: v1
kind: Service
metadata:
  name: ingest-service
  namespace: kafka
spec:
  selector:
    app: ingest-service
  ports:
    - port: 50051
      targetPort: 50051
      protocol: TCP
      name: grpc
    - port: 9100
      targetPort: 9100
      protocol: TCP
      name: metrics
  type: ClusterIP
