// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: transaction.proto

package fraudv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Transaction struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionId   string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CardId          string                 `protobuf:"bytes,3,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	Amount          float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency        string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Merchant        string                 `protobuf:"bytes,6,opt,name=merchant,proto3" json:"merchant,omitempty"`
	Location        string                 `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"` // e.g. "IN-DEL", "US-NYC"
	TransactionTime *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=transaction_time,json=transactionTime,proto3" json:"transaction_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *Transaction) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Transaction) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *Transaction) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transaction) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Transaction) GetMerchant() string {
	if x != nil {
		return x.Merchant
	}
	return ""
}

func (x *Transaction) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Transaction) GetTransactionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.TransactionTime
	}
	return nil
}

type SubmitTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTransactionRequest) Reset() {
	*x = SubmitTransactionRequest{}
	mi := &file_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTransactionRequest) ProtoMessage() {}

func (x *SubmitTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTransactionRequest.ProtoReflect.Descriptor instead.
func (*SubmitTransactionRequest) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitTransactionRequest) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type SubmitTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTransactionResponse) Reset() {
	*x = SubmitTransactionResponse{}
	mi := &file_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTransactionResponse) ProtoMessage() {}

func (x *SubmitTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTransactionResponse.ProtoReflect.Descriptor instead.
func (*SubmitTransactionResponse) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitTransactionResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *SubmitTransactionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ScoredTransaction struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionId   string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CardId          string                 `protobuf:"bytes,3,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	Amount          float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency        string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Merchant        string                 `protobuf:"bytes,6,opt,name=merchant,proto3" json:"merchant,omitempty"`
	Location        string                 `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	TransactionTime *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=transaction_time,json=transactionTime,proto3" json:"transaction_time,omitempty"`
	RiskScore       float64                `protobuf:"fixed64,9,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	Flagged         bool                   `protobuf:"varint,10,opt,name=flagged,proto3" json:"flagged,omitempty"`
	RiskReasons     []string               `protobuf:"bytes,11,rep,name=risk_reasons,json=riskReasons,proto3" json:"risk_reasons,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ScoredTransaction) Reset() {
	*x = ScoredTransaction{}
	mi := &file_transaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoredTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoredTransaction) ProtoMessage() {}

func (x *ScoredTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoredTransaction.ProtoReflect.Descriptor instead.
func (*ScoredTransaction) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{3}
}

func (x *ScoredTransaction) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *ScoredTransaction) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ScoredTransaction) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *ScoredTransaction) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ScoredTransaction) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *ScoredTransaction) GetMerchant() string {
	if x != nil {
		return x.Merchant
	}
	return ""
}

func (x *ScoredTransaction) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *ScoredTransaction) GetTransactionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.TransactionTime
	}
	return nil
}

func (x *ScoredTransaction) GetRiskScore() float64 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *ScoredTransaction) GetFlagged() bool {
	if x != nil {
		return x.Flagged
	}
	return false
}

func (x *ScoredTransaction) GetRiskReasons() []string {
	if x != nil {
		return x.RiskReasons
	}
	return nil
}

type GetFlaggedTransactionsTodayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFlaggedTransactionsTodayRequest) Reset() {
	*x = GetFlaggedTransactionsTodayRequest{}
	mi := &file_transaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFlaggedTransactionsTodayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlaggedTransactionsTodayRequest) ProtoMessage() {}

func (x *GetFlaggedTransactionsTodayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlaggedTransactionsTodayRequest.ProtoReflect.Descriptor instead.
func (*GetFlaggedTransactionsTodayRequest) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{4}
}

func (x *GetFlaggedTransactionsTodayRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetFlaggedTransactionsTodayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*ScoredTransaction   `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFlaggedTransactionsTodayResponse) Reset() {
	*x = GetFlaggedTransactionsTodayResponse{}
	mi := &file_transaction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFlaggedTransactionsTodayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlaggedTransactionsTodayResponse) ProtoMessage() {}

func (x *GetFlaggedTransactionsTodayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlaggedTransactionsTodayResponse.ProtoReflect.Descriptor instead.
func (*GetFlaggedTransactionsTodayResponse) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{5}
}

func (x *GetFlaggedTransactionsTodayResponse) GetTransactions() []*ScoredTransaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type GetUserFraudScoreHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserFraudScoreHistoryRequest) Reset() {
	*x = GetUserFraudScoreHistoryRequest{}
	mi := &file_transaction_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserFraudScoreHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserFraudScoreHistoryRequest) ProtoMessage() {}

func (x *GetUserFraudScoreHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserFraudScoreHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetUserFraudScoreHistoryRequest) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserFraudScoreHistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserFraudScoreHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetUserFraudScoreHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*ScoredTransaction   `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserFraudScoreHistoryResponse) Reset() {
	*x = GetUserFraudScoreHistoryResponse{}
	mi := &file_transaction_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserFraudScoreHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserFraudScoreHistoryResponse) ProtoMessage() {}

func (x *GetUserFraudScoreHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserFraudScoreHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetUserFraudScoreHistoryResponse) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserFraudScoreHistoryResponse) GetTransactions() []*ScoredTransaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

var File_transaction_proto protoreflect.FileDescriptor

const file_transaction_proto_rawDesc = "" +
	"\n" +
	"\x11transaction.proto\x12\x11frauddetection.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x99\x02\n" +
	"\vTransaction\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\acard_id\x18\x03 \x01(\tR\x06cardId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x1a\n" +
	"\bmerchant\x18\x06 \x01(\tR\bmerchant\x12\x1a\n" +
	"\blocation\x18\a \x01(\tR\blocation\x12E\n" +
	"\x10transaction_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x0ftransactionTime\"\\\n" +
	"\x18SubmitTransactionRequest\x12@\n" +
	"\vtransaction\x18\x01 \x01(\v2\x1e.frauddetection.v1.TransactionR\vtransaction\"Q\n" +
	"\x19SubmitTransactionResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xfb\x02\n" +
	"\x11ScoredTransaction\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\acard_id\x18\x03 \x01(\tR\x06cardId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x1a\n" +
	"\bmerchant\x18\x06 \x01(\tR\bmerchant\x12\x1a\n" +
	"\blocation\x18\a \x01(\tR\blocation\x12E\n" +
	"\x10transaction_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x0ftransactionTime\x12\x1d\n" +
	"\n" +
	"risk_score\x18\t \x01(\x01R\triskScore\x12\x18\n" +
	"\aflagged\x18\n" +
	" \x01(\bR\aflagged\x12!\n" +
	"\frisk_reasons\x18\v \x03(\tR\vriskReasons\":\n" +
	"\"GetFlaggedTransactionsTodayRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"o\n" +
	"#GetFlaggedTransactionsTodayResponse\x12H\n" +
	"\ftransactions\x18\x01 \x03(\v2$.frauddetection.v1.ScoredTransactionR\ftransactions\"P\n" +
	"\x1fGetUserFraudScoreHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"l\n" +
	" GetUserFraudScoreHistoryResponse\x12H\n" +
	"\ftransactions\x18\x01 \x03(\v2$.frauddetection.v1.ScoredTransactionR\ftransactions2\x7f\n" +
	"\rIngestService\x12n\n" +
	"\x11SubmitTransaction\x12+.frauddetection.v1.SubmitTransactionRequest\x1a,.frauddetection.v1.SubmitTransactionResponse2\xa3\x02\n" +
	"\fQueryService\x12\x8c\x01\n" +
	"\x1bGetFlaggedTransactionsToday\x125.frauddetection.v1.GetFlaggedTransactionsTodayRequest\x1a6.frauddetection.v1.GetFlaggedTransactionsTodayResponse\x12\x83\x01\n" +
	"\x18GetUserFraudScoreHistory\x122.frauddetection.v1.GetUserFraudScoreHistoryRequest\x1a3.frauddetection.v1.GetUserFraudScoreHistoryResponseB,Z*github.com/frauddetection/proto/v1;fraudv1b\x06proto3"

var (
	file_transaction_proto_rawDescOnce sync.Once
	file_transaction_proto_rawDescData []byte
)

func file_transaction_proto_rawDescGZIP() []byte {
	file_transaction_proto_rawDescOnce.Do(func() {
		file_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transaction_proto_rawDesc), len(file_transaction_proto_rawDesc)))
	})
	return file_transaction_proto_rawDescData
}

var file_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_transaction_proto_goTypes = []any{
	(*Transaction)(nil),                         // 0: frauddetection.v1.Transaction
	(*SubmitTransactionRequest)(nil),            // 1: frauddetection.v1.SubmitTransactionRequest
	(*SubmitTransactionResponse)(nil),           // 2: frauddetection.v1.SubmitTransactionResponse
	(*ScoredTransaction)(nil),                   // 3: frauddetection.v1.ScoredTransaction
	(*GetFlaggedTransactionsTodayRequest)(nil),  // 4: frauddetection.v1.GetFlaggedTransactionsTodayRequest
	(*GetFlaggedTransactionsTodayResponse)(nil), // 5: frauddetection.v1.GetFlaggedTransactionsTodayResponse
	(*GetUserFraudScoreHistoryRequest)(nil),     // 6: frauddetection.v1.GetUserFraudScoreHistoryRequest
	(*GetUserFraudScoreHistoryResponse)(nil),    // 7: frauddetection.v1.GetUserFraudScoreHistoryResponse
	(*timestamppb.Timestamp)(nil),               // 8: google.protobuf.Timestamp
}
var file_transaction_proto_depIdxs = []int32{
	8, // 0: frauddetection.v1.Transaction.transaction_time:type_name -> google.protobuf.Timestamp
	0, // 1: frauddetection.v1.SubmitTransactionRequest.transaction:type_name -> frauddetection.v1.Transaction
	8, // 2: frauddetection.v1.ScoredTransaction.transaction_time:type_name -> google.protobuf.Timestamp
	3, // 3: frauddetection.v1.GetFlaggedTransactionsTodayResponse.transactions:type_name -> frauddetection.v1.ScoredTransaction
	3, // 4: frauddetection.v1.GetUserFraudScoreHistoryResponse.transactions:type_name -> frauddetection.v1.ScoredTransaction
	1, // 5: frauddetection.v1.IngestService.SubmitTransaction:input_type -> frauddetection.v1.SubmitTransactionRequest
	4, // 6: frauddetection.v1.QueryService.GetFlaggedTransactionsToday:input_type -> frauddetection.v1.GetFlaggedTransactionsTodayRequest
	6, // 7: frauddetection.v1.QueryService.GetUserFraudScoreHistory:input_type -> frauddetection.v1.GetUserFraudScoreHistoryRequest
	2, // 8: frauddetection.v1.IngestService.SubmitTransaction:output_type -> frauddetection.v1.SubmitTransactionResponse
	5, // 9: frauddetection.v1.QueryService.GetFlaggedTransactionsToday:output_type -> frauddetection.v1.GetFlaggedTransactionsTodayResponse
	7, // 10: frauddetection.v1.QueryService.GetUserFraudScoreHistory:output_type -> frauddetection.v1.GetUserFraudScoreHistoryResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_transaction_proto_init() }
func file_transaction_proto_init() {
	if File_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transaction_proto_rawDesc), len(file_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_transaction_proto_goTypes,
		DependencyIndexes: file_transaction_proto_depIdxs,
		MessageInfos:      file_transaction_proto_msgTypes,
	}.Build()
	File_transaction_proto = out.File
	file_transaction_proto_goTypes = nil
	file_transaction_proto_depIdxs = nil
}
